### PR TITLE
Fix install_requires and add installation of grader_support package

### PR DESCRIPTION
**Pull request by TheVinhLuong102**
Hi authors, we've made some small fixes to the setup.py script for your consideration.

Thank you very much!

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @TheVinhLuong102!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by natabene** [comment]
@TheVinhLuong102 Thank you for the contribution. Once your CLA form have been processed, I will update here and we will be able to review your code.

**Comment by TheVinhLuong102** [comment]
@natabene thank you so much!

I'm contributing on the behalf of STEAM for Vietnam Foundation, an educational non-profit org who is actively using and extending Open edX. We would like to submit regular enhancements and fixes for your review.


I've received and signed the DocuSign from Eden Huthmacher. Looking forward to formally collaborating with you. :)

Vinh

**Comment by TheVinhLuong102** [comment]
@natabene actually I received the "TCRIL Individual Contributor License Agreement" doc instead. Am I supposed to sign a different one? Could you guide me through? Thank you Natalia!

**Comment by natabene** [comment]
@TheVinhLuong102 Just checking if you had any luck with getting entity agreement signed?

**Comment by natabene** [comment]
The CLA check is green, wonderful. This can be reviewed by our teams.

**Comment by ProductRyan** [comment]
Creating a JIRA ticket for internal tracking:
https://2u-internal.atlassian.net/browse/AU-942

**Comment by itsjeyd** [comment]
Hi @ProductRyan and @mattcarter, just checking in to see if you had a chance to schedule https://2u-internal.atlassian.net/browse/AU-942 yet?

**Review by mattcarter — APPROVED** [review]
approved.

**Comment by openedx-webhooks** [comment]
@TheVinhLuong102 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xqueue-watcher&entry.867055334=https://github.com/openedx/xqueue-watcher/pull/82&entry.1484655318=https://github.com/TheVinhLuong102&entry.752974735=2022-08-20+23:34&entry.1917517419=2023-02-01+15:33&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by itsjeyd** [comment]
Thanks @mattcarter!

**Comment by TheVinhLuong102** [comment]
Thank you so much @itsjeyd @mattcarter @ProductRyan @natabene et al.!

I'll work with my colleagues at STEAM for Vietnam and open a couple more PRs. :)

**Comment by itsjeyd** [comment]
That sounds great @TheVinhLuong102! Looking forward to future contributions from you and your team.

**Pull request merged**
